module Stagehand
  class Action = Stagehand::Models::Action

  module ModelConfig = Stagehand::Models::ModelConfig

  class SessionActParams = Stagehand::Models::SessionActParams

  class SessionEndParams = Stagehand::Models::SessionEndParams

  class SessionExecuteParams = Stagehand::Models::SessionExecuteParams

  class SessionExtractParams = Stagehand::Models::SessionExtractParams

  class SessionNavigateParams = Stagehand::Models::SessionNavigateParams

  class SessionObserveParams = Stagehand::Models::SessionObserveParams

  class SessionStartParams = Stagehand::Models::SessionStartParams
end
