configured_endpoints: 7
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/browserbase%2Fstagehand-d91dfd9ce727aefac56505ac86feb5cc665d3d5cef80ff17605f45e09b258251.yml
openapi_spec_hash: 0d1cae70e9d1debc5ac1a69fc665af37
config_hash: 64c9cc393de93af70e11dbf0b1ba9388
