module Stagehand
  module Models
    type action =
      {
        description: String,
        selector: String,
        arguments: ::Array[String],
        method_: String
      }

    class Action < Stagehand::Internal::Type::BaseModel
      attr_accessor description: String

      attr_accessor selector: String

      attr_reader arguments: ::Array[String]?

      def arguments=: (::Array[String]) -> ::Array[String]

      attr_reader method_: String?

      def method_=: (String) -> String

      def initialize: (
        description: String,
        selector: String,
        ?arguments: ::Array[String],
        ?method_: String
      ) -> void

      def to_hash: -> {
        description: String,
        selector: String,
        arguments: ::Array[String],
        method_: String
      }
    end
  end
end
