module Stagehand
  module Models
    type model_config =
      {
        model_name: String,
        api_key: String,
        base_url: String,
        provider: Stagehand::Models::ModelConfig::provider
      }

    class ModelConfig < Stagehand::Internal::Type::BaseModel
      attr_accessor model_name: String

      attr_reader api_key: String?

      def api_key=: (String) -> String

      attr_reader base_url: String?

      def base_url=: (String) -> String

      attr_reader provider: Stagehand::Models::ModelConfig::provider?

      def provider=: (
        Stagehand::Models::ModelConfig::provider
      ) -> Stagehand::Models::ModelConfig::provider

      def initialize: (
        model_name: String,
        ?api_key: String,
        ?base_url: String,
        ?provider: Stagehand::Models::ModelConfig::provider
      ) -> void

      def to_hash: -> {
        model_name: String,
        api_key: String,
        base_url: String,
        provider: Stagehand::Models::ModelConfig::provider
      }

      type provider = :openai | :anthropic | :google | :microsoft

      module Provider
        extend Stagehand::Internal::Type::Enum

        OPENAI: :openai
        ANTHROPIC: :anthropic
        GOOGLE: :google
        MICROSOFT: :microsoft

        def self?.values: -> ::Array[Stagehand::Models::ModelConfig::provider]
      end
    end
  end
end
