module Stagehand
  module Models
    type model_config = String | Stagehand::ModelConfig::UnionMember1

    module ModelConfig
      extend Stagehand::Internal::Type::Union

      type union_member1 =
        { model_name: String, api_key: String, base_url: String }

      class UnionMember1 < Stagehand::Internal::Type::BaseModel
        attr_accessor model_name: String

        attr_reader api_key: String?

        def api_key=: (String) -> String

        attr_reader base_url: String?

        def base_url=: (String) -> String

        def initialize: (
          model_name: String,
          ?api_key: String,
          ?base_url: String
        ) -> void

        def to_hash: -> {
          model_name: String,
          api_key: String,
          base_url: String
        }
      end

      def self?.variants: -> ::Array[Stagehand::Models::model_config]
    end
  end
end
