module Stagehand
  module Models
    type session_navigate_params =
      {
        url: String,
        frame_id: String,
        options: Stagehand::SessionNavigateParams::Options,
        x_stream_response: Stagehand::Models::SessionNavigateParams::x_stream_response
      }
      & Stagehand::Internal::Type::request_parameters

    class SessionNavigateParams < Stagehand::Internal::Type::BaseModel
      extend Stagehand::Internal::Type::RequestParameters::Converter
      include Stagehand::Internal::Type::RequestParameters

      attr_accessor url: String

      attr_reader frame_id: String?

      def frame_id=: (String) -> String

      attr_reader options: Stagehand::SessionNavigateParams::Options?

      def options=: (
        Stagehand::SessionNavigateParams::Options
      ) -> Stagehand::SessionNavigateParams::Options

      attr_reader x_stream_response: Stagehand::Models::SessionNavigateParams::x_stream_response?

      def x_stream_response=: (
        Stagehand::Models::SessionNavigateParams::x_stream_response
      ) -> Stagehand::Models::SessionNavigateParams::x_stream_response

      def initialize: (
        url: String,
        ?frame_id: String,
        ?options: Stagehand::SessionNavigateParams::Options,
        ?x_stream_response: Stagehand::Models::SessionNavigateParams::x_stream_response,
        ?request_options: Stagehand::request_opts
      ) -> void

      def to_hash: -> {
        url: String,
        frame_id: String,
        options: Stagehand::SessionNavigateParams::Options,
        x_stream_response: Stagehand::Models::SessionNavigateParams::x_stream_response,
        request_options: Stagehand::RequestOptions
      }

      type options =
        {
          wait_until: Stagehand::Models::SessionNavigateParams::Options::wait_until
        }

      class Options < Stagehand::Internal::Type::BaseModel
        attr_reader wait_until: Stagehand::Models::SessionNavigateParams::Options::wait_until?

        def wait_until=: (
          Stagehand::Models::SessionNavigateParams::Options::wait_until
        ) -> Stagehand::Models::SessionNavigateParams::Options::wait_until

        def initialize: (
          ?wait_until: Stagehand::Models::SessionNavigateParams::Options::wait_until
        ) -> void

        def to_hash: -> {
          wait_until: Stagehand::Models::SessionNavigateParams::Options::wait_until
        }

        type wait_until = :load | :domcontentloaded | :networkidle

        module WaitUntil
          extend Stagehand::Internal::Type::Enum

          LOAD: :load
          DOMCONTENTLOADED: :domcontentloaded
          NETWORKIDLE: :networkidle

          def self?.values: -> ::Array[Stagehand::Models::SessionNavigateParams::Options::wait_until]
        end
      end

      type x_stream_response = :true | :false

      module XStreamResponse
        extend Stagehand::Internal::Type::Enum

        TRUE: :true
        FALSE: :false

        def self?.values: -> ::Array[Stagehand::Models::SessionNavigateParams::x_stream_response]
      end
    end
  end
end
