module Stagehand
  module Models
    type session_execute_params =
      {
        agent_config: Stagehand::SessionExecuteParams::AgentConfig,
        execute_options: Stagehand::SessionExecuteParams::ExecuteOptions,
        frame_id: String,
        x_language: Stagehand::Models::SessionExecuteParams::x_language,
        x_sdk_version: String,
        x_sent_at: Time,
        x_stream_response: Stagehand::Models::SessionExecuteParams::x_stream_response
      }
      & Stagehand::Internal::Type::request_parameters

    class SessionExecuteParams < Stagehand::Internal::Type::BaseModel
      extend Stagehand::Internal::Type::RequestParameters::Converter
      include Stagehand::Internal::Type::RequestParameters

      attr_accessor agent_config: Stagehand::SessionExecuteParams::AgentConfig

      attr_accessor execute_options: Stagehand::SessionExecuteParams::ExecuteOptions

      attr_reader frame_id: String?

      def frame_id=: (String) -> String

      attr_reader x_language: Stagehand::Models::SessionExecuteParams::x_language?

      def x_language=: (
        Stagehand::Models::SessionExecuteParams::x_language
      ) -> Stagehand::Models::SessionExecuteParams::x_language

      attr_reader x_sdk_version: String?

      def x_sdk_version=: (String) -> String

      attr_reader x_sent_at: Time?

      def x_sent_at=: (Time) -> Time

      attr_reader x_stream_response: Stagehand::Models::SessionExecuteParams::x_stream_response?

      def x_stream_response=: (
        Stagehand::Models::SessionExecuteParams::x_stream_response
      ) -> Stagehand::Models::SessionExecuteParams::x_stream_response

      def initialize: (
        agent_config: Stagehand::SessionExecuteParams::AgentConfig,
        execute_options: Stagehand::SessionExecuteParams::ExecuteOptions,
        ?frame_id: String,
        ?x_language: Stagehand::Models::SessionExecuteParams::x_language,
        ?x_sdk_version: String,
        ?x_sent_at: Time,
        ?x_stream_response: Stagehand::Models::SessionExecuteParams::x_stream_response,
        ?request_options: Stagehand::request_opts
      ) -> void

      def to_hash: -> {
        agent_config: Stagehand::SessionExecuteParams::AgentConfig,
        execute_options: Stagehand::SessionExecuteParams::ExecuteOptions,
        frame_id: String,
        x_language: Stagehand::Models::SessionExecuteParams::x_language,
        x_sdk_version: String,
        x_sent_at: Time,
        x_stream_response: Stagehand::Models::SessionExecuteParams::x_stream_response,
        request_options: Stagehand::RequestOptions
      }

      type agent_config =
        {
          cua: bool,
          model: Stagehand::Models::model_config,
          system_prompt: String
        }

      class AgentConfig < Stagehand::Internal::Type::BaseModel
        attr_reader cua: bool?

        def cua=: (bool) -> bool

        attr_reader model: Stagehand::Models::model_config?

        def model=: (
          Stagehand::Models::model_config
        ) -> Stagehand::Models::model_config

        attr_reader system_prompt: String?

        def system_prompt=: (String) -> String

        def initialize: (
          ?cua: bool,
          ?model: Stagehand::Models::model_config,
          ?system_prompt: String
        ) -> void

        def to_hash: -> {
          cua: bool,
          model: Stagehand::Models::model_config,
          system_prompt: String
        }
      end

      type execute_options =
        { instruction: String, highlight_cursor: bool, max_steps: Float }

      class ExecuteOptions < Stagehand::Internal::Type::BaseModel
        attr_accessor instruction: String

        attr_reader highlight_cursor: bool?

        def highlight_cursor=: (bool) -> bool

        attr_reader max_steps: Float?

        def max_steps=: (Float) -> Float

        def initialize: (
          instruction: String,
          ?highlight_cursor: bool,
          ?max_steps: Float
        ) -> void

        def to_hash: -> {
          instruction: String,
          highlight_cursor: bool,
          max_steps: Float
        }
      end

      type x_language = :typescript | :python | :playground

      module XLanguage
        extend Stagehand::Internal::Type::Enum

        TYPESCRIPT: :typescript
        PYTHON: :python
        PLAYGROUND: :playground

        def self?.values: -> ::Array[Stagehand::Models::SessionExecuteParams::x_language]
      end

      type x_stream_response = :true | :false

      module XStreamResponse
        extend Stagehand::Internal::Type::Enum

        TRUE: :true
        FALSE: :false

        def self?.values: -> ::Array[Stagehand::Models::SessionExecuteParams::x_stream_response]
      end
    end
  end
end
