module Stagehand
  module Models
    type session_observe_params =
      {
        id: String,
        frame_id: String?,
        instruction: String,
        options: Stagehand::SessionObserveParams::Options,
        x_stream_response: Stagehand::Models::SessionObserveParams::x_stream_response
      }
      & Stagehand::Internal::Type::request_parameters

    class SessionObserveParams < Stagehand::Internal::Type::BaseModel
      extend Stagehand::Internal::Type::RequestParameters::Converter
      include Stagehand::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_accessor frame_id: String?

      attr_reader instruction: String?

      def instruction=: (String) -> String

      attr_reader options: Stagehand::SessionObserveParams::Options?

      def options=: (
        Stagehand::SessionObserveParams::Options
      ) -> Stagehand::SessionObserveParams::Options

      attr_reader x_stream_response: Stagehand::Models::SessionObserveParams::x_stream_response?

      def x_stream_response=: (
        Stagehand::Models::SessionObserveParams::x_stream_response
      ) -> Stagehand::Models::SessionObserveParams::x_stream_response

      def initialize: (
        id: String,
        ?frame_id: String?,
        ?instruction: String,
        ?options: Stagehand::SessionObserveParams::Options,
        ?x_stream_response: Stagehand::Models::SessionObserveParams::x_stream_response,
        ?request_options: Stagehand::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        frame_id: String?,
        instruction: String,
        options: Stagehand::SessionObserveParams::Options,
        x_stream_response: Stagehand::Models::SessionObserveParams::x_stream_response,
        request_options: Stagehand::RequestOptions
      }

      type options =
        {
          model: Stagehand::Models::SessionObserveParams::Options::model,
          selector: String,
          timeout: Float,
          variables: ::Hash[Symbol, Stagehand::Models::SessionObserveParams::Options::variable]
        }

      class Options < Stagehand::Internal::Type::BaseModel
        attr_reader model: Stagehand::Models::SessionObserveParams::Options::model?

        def model=: (
          Stagehand::Models::SessionObserveParams::Options::model
        ) -> Stagehand::Models::SessionObserveParams::Options::model

        attr_reader selector: String?

        def selector=: (String) -> String

        attr_reader timeout: Float?

        def timeout=: (Float) -> Float

        attr_reader variables: ::Hash[Symbol, Stagehand::Models::SessionObserveParams::Options::variable]?

        def variables=: (
          ::Hash[Symbol, Stagehand::Models::SessionObserveParams::Options::variable]
        ) -> ::Hash[Symbol, Stagehand::Models::SessionObserveParams::Options::variable]

        def initialize: (
          ?model: Stagehand::Models::SessionObserveParams::Options::model,
          ?selector: String,
          ?timeout: Float,
          ?variables: ::Hash[Symbol, Stagehand::Models::SessionObserveParams::Options::variable]
        ) -> void

        def to_hash: -> {
          model: Stagehand::Models::SessionObserveParams::Options::model,
          selector: String,
          timeout: Float,
          variables: ::Hash[Symbol, Stagehand::Models::SessionObserveParams::Options::variable]
        }

        type model = Stagehand::ModelConfig | String

        module Model
          extend Stagehand::Internal::Type::Union

          def self?.variants: -> ::Array[Stagehand::Models::SessionObserveParams::Options::model]
        end

        type variable =
          String
          | Float
          | bool
          | Stagehand::SessionObserveParams::Options::Variable::UnionMember3

        module Variable
          extend Stagehand::Internal::Type::Union

          type union_member3 =
            {
              value: Stagehand::Models::SessionObserveParams::Options::Variable::UnionMember3::value,
              description: String
            }

          class UnionMember3 < Stagehand::Internal::Type::BaseModel
            attr_accessor value: Stagehand::Models::SessionObserveParams::Options::Variable::UnionMember3::value

            attr_reader description: String?

            def description=: (String) -> String

            def initialize: (
              value: Stagehand::Models::SessionObserveParams::Options::Variable::UnionMember3::value,
              ?description: String
            ) -> void

            def to_hash: -> {
              value: Stagehand::Models::SessionObserveParams::Options::Variable::UnionMember3::value,
              description: String
            }

            type value = String | Float | bool

            module Value
              extend Stagehand::Internal::Type::Union

              def self?.variants: -> ::Array[Stagehand::Models::SessionObserveParams::Options::Variable::UnionMember3::value]
            end
          end

          def self?.variants: -> ::Array[Stagehand::Models::SessionObserveParams::Options::variable]
        end
      end

      type x_stream_response = :true | :false

      module XStreamResponse
        extend Stagehand::Internal::Type::Enum

        TRUE: :true
        FALSE: :false

        def self?.values: -> ::Array[Stagehand::Models::SessionObserveParams::x_stream_response]
      end
    end
  end
end
