module Stagehand
  module Models
    type session_act_response =
      { actions: ::Array[Stagehand::Action], message: String, success: bool }

    class SessionActResponse < Stagehand::Internal::Type::BaseModel
      attr_accessor actions: ::Array[Stagehand::Action]

      attr_accessor message: String

      attr_accessor success: bool

      def initialize: (
        actions: ::Array[Stagehand::Action],
        message: String,
        success: bool
      ) -> void

      def to_hash: -> {
        actions: ::Array[Stagehand::Action],
        message: String,
        success: bool
      }
    end
  end
end
