module Stagehand
  module Models
    type session_end_response = { success: true }

    class SessionEndResponse < Stagehand::Internal::Type::BaseModel
      attr_accessor success: true

      def initialize: (?success: true) -> void

      def to_hash: -> { success: true }
    end
  end
end
