module Stagehand
  module Models
    type session_end_params =
      {
        _force_body: top,
        x_stream_response: Stagehand::Models::SessionEndParams::x_stream_response
      }
      & Stagehand::Internal::Type::request_parameters

    class SessionEndParams < Stagehand::Internal::Type::BaseModel
      extend Stagehand::Internal::Type::RequestParameters::Converter
      include Stagehand::Internal::Type::RequestParameters

      attr_reader _force_body: top?

      def _force_body=: (top) -> top

      attr_reader x_stream_response: Stagehand::Models::SessionEndParams::x_stream_response?

      def x_stream_response=: (
        Stagehand::Models::SessionEndParams::x_stream_response
      ) -> Stagehand::Models::SessionEndParams::x_stream_response

      def initialize: (
        ?_force_body: top,
        ?x_stream_response: Stagehand::Models::SessionEndParams::x_stream_response,
        ?request_options: Stagehand::request_opts
      ) -> void

      def to_hash: -> {
        _force_body: top,
        x_stream_response: Stagehand::Models::SessionEndParams::x_stream_response,
        request_options: Stagehand::RequestOptions
      }

      type x_stream_response = :true | :false

      module XStreamResponse
        extend Stagehand::Internal::Type::Enum

        TRUE: :true
        FALSE: :false

        def self?.values: -> ::Array[Stagehand::Models::SessionEndParams::x_stream_response]
      end
    end
  end
end
