module Stagehand
  module Models
    type session_navigate_response =
      {
        data: Stagehand::Models::SessionNavigateResponse::Data,
        success: Stagehand::Models::SessionNavigateResponse::success
      }

    class SessionNavigateResponse < Stagehand::Internal::Type::BaseModel
      attr_accessor data: Stagehand::Models::SessionNavigateResponse::Data

      attr_accessor success: Stagehand::Models::SessionNavigateResponse::success

      def initialize: (
        data: Stagehand::Models::SessionNavigateResponse::Data,
        success: Stagehand::Models::SessionNavigateResponse::success
      ) -> void

      def to_hash: -> {
        data: Stagehand::Models::SessionNavigateResponse::Data,
        success: Stagehand::Models::SessionNavigateResponse::success
      }

      type data = { result: top, action_id: String }

      class Data < Stagehand::Internal::Type::BaseModel
        attr_accessor result: top

        attr_reader action_id: String?

        def action_id=: (String) -> String

        def initialize: (result: top, ?action_id: String) -> void

        def to_hash: -> { result: top, action_id: String }
      end

      type success = true

      module Success
        extend Stagehand::Internal::Type::Enum

        TRUE: true

        def self?.values: -> ::Array[Stagehand::Models::SessionNavigateResponse::success]
      end
    end
  end
end
