module Stagehand
  module Models
    type session_start_params =
      {
        browserbase_api_key: String,
        browserbase_project_id: String,
        dom_settle_timeout: Integer,
        model: String,
        self_heal: bool,
        system_prompt: String,
        verbose: Integer
      }
      & Stagehand::Internal::Type::request_parameters

    class SessionStartParams < Stagehand::Internal::Type::BaseModel
      extend Stagehand::Internal::Type::RequestParameters::Converter
      include Stagehand::Internal::Type::RequestParameters

      attr_accessor browserbase_api_key: String

      attr_accessor browserbase_project_id: String

      attr_reader dom_settle_timeout: Integer?

      def dom_settle_timeout=: (Integer) -> Integer

      attr_reader model: String?

      def model=: (String) -> String

      attr_reader self_heal: bool?

      def self_heal=: (bool) -> bool

      attr_reader system_prompt: String?

      def system_prompt=: (String) -> String

      attr_reader verbose: Integer?

      def verbose=: (Integer) -> Integer

      def initialize: (
        browserbase_api_key: String,
        browserbase_project_id: String,
        ?dom_settle_timeout: Integer,
        ?model: String,
        ?self_heal: bool,
        ?system_prompt: String,
        ?verbose: Integer,
        ?request_options: Stagehand::request_opts
      ) -> void

      def to_hash: -> {
        browserbase_api_key: String,
        browserbase_project_id: String,
        dom_settle_timeout: Integer,
        model: String,
        self_heal: bool,
        system_prompt: String,
        verbose: Integer,
        request_options: Stagehand::RequestOptions
      }
    end
  end
end
