module Stagehand
  module Models
    type session_replay_response =
      { data: Stagehand::Models::SessionReplayResponse::Data, success: bool }

    class SessionReplayResponse < Stagehand::Internal::Type::BaseModel
      attr_accessor data: Stagehand::Models::SessionReplayResponse::Data

      attr_accessor success: bool

      def initialize: (
        data: Stagehand::Models::SessionReplayResponse::Data,
        success: bool
      ) -> void

      def to_hash: -> {
        data: Stagehand::Models::SessionReplayResponse::Data,
        success: bool
      }

      type data =
        {
          pages: ::Array[Stagehand::Models::SessionReplayResponse::Data::Page],
          client_language: String
        }

      class Data < Stagehand::Internal::Type::BaseModel
        attr_accessor pages: ::Array[Stagehand::Models::SessionReplayResponse::Data::Page]

        attr_reader client_language: String?

        def client_language=: (String) -> String

        def initialize: (
          pages: ::Array[Stagehand::Models::SessionReplayResponse::Data::Page],
          ?client_language: String
        ) -> void

        def to_hash: -> {
          pages: ::Array[Stagehand::Models::SessionReplayResponse::Data::Page],
          client_language: String
        }

        type page =
          {
            actions: ::Array[Stagehand::Models::SessionReplayResponse::Data::Page::Action],
            duration: Float,
            timestamp: Float,
            url: String
          }

        class Page < Stagehand::Internal::Type::BaseModel
          attr_accessor actions: ::Array[Stagehand::Models::SessionReplayResponse::Data::Page::Action]

          attr_accessor duration: Float

          attr_accessor timestamp: Float

          attr_accessor url: String

          def initialize: (
            actions: ::Array[Stagehand::Models::SessionReplayResponse::Data::Page::Action],
            duration: Float,
            timestamp: Float,
            url: String
          ) -> void

          def to_hash: -> {
            actions: ::Array[Stagehand::Models::SessionReplayResponse::Data::Page::Action],
            duration: Float,
            timestamp: Float,
            url: String
          }

          type action =
            {
              method_: String,
              parameters: ::Hash[Symbol, top],
              result: ::Hash[Symbol, top],
              timestamp: Float,
              end_time: Float,
              token_usage: Stagehand::Models::SessionReplayResponse::Data::Page::Action::TokenUsage
            }

          class Action < Stagehand::Internal::Type::BaseModel
            attr_accessor method_: String

            attr_accessor parameters: ::Hash[Symbol, top]

            attr_accessor result: ::Hash[Symbol, top]

            attr_accessor timestamp: Float

            attr_reader end_time: Float?

            def end_time=: (Float) -> Float

            attr_reader token_usage: Stagehand::Models::SessionReplayResponse::Data::Page::Action::TokenUsage?

            def token_usage=: (
              Stagehand::Models::SessionReplayResponse::Data::Page::Action::TokenUsage
            ) -> Stagehand::Models::SessionReplayResponse::Data::Page::Action::TokenUsage

            def initialize: (
              method_: String,
              parameters: ::Hash[Symbol, top],
              result: ::Hash[Symbol, top],
              timestamp: Float,
              ?end_time: Float,
              ?token_usage: Stagehand::Models::SessionReplayResponse::Data::Page::Action::TokenUsage
            ) -> void

            def to_hash: -> {
              method_: String,
              parameters: ::Hash[Symbol, top],
              result: ::Hash[Symbol, top],
              timestamp: Float,
              end_time: Float,
              token_usage: Stagehand::Models::SessionReplayResponse::Data::Page::Action::TokenUsage
            }

            type token_usage =
              {
                cost: Float,
                input_tokens: Float,
                output_tokens: Float,
                time_ms: Float
              }

            class TokenUsage < Stagehand::Internal::Type::BaseModel
              attr_reader cost: Float?

              def cost=: (Float) -> Float

              attr_reader input_tokens: Float?

              def input_tokens=: (Float) -> Float

              attr_reader output_tokens: Float?

              def output_tokens=: (Float) -> Float

              attr_reader time_ms: Float?

              def time_ms=: (Float) -> Float

              def initialize: (
                ?cost: Float,
                ?input_tokens: Float,
                ?output_tokens: Float,
                ?time_ms: Float
              ) -> void

              def to_hash: -> {
                cost: Float,
                input_tokens: Float,
                output_tokens: Float,
                time_ms: Float
              }
            end
          end
        end
      end
    end
  end
end
