module Stagehand
  module Models
    type session_extract_params =
      {
        body: top,
        x_language: top,
        x_sdk_version: top,
        x_sent_at: top,
        x_stream_response: top
      }
      & Stagehand::Internal::Type::request_parameters

    class SessionExtractParams < Stagehand::Internal::Type::BaseModel
      extend Stagehand::Internal::Type::RequestParameters::Converter
      include Stagehand::Internal::Type::RequestParameters

      attr_reader body: top?

      def body=: (top) -> top

      attr_reader x_language: top?

      def x_language=: (top) -> top

      attr_reader x_sdk_version: top?

      def x_sdk_version=: (top) -> top

      attr_reader x_sent_at: top?

      def x_sent_at=: (top) -> top

      attr_reader x_stream_response: top?

      def x_stream_response=: (top) -> top

      def initialize: (
        ?body: top,
        ?x_language: top,
        ?x_sdk_version: top,
        ?x_sent_at: top,
        ?x_stream_response: top,
        ?request_options: Stagehand::request_opts
      ) -> void

      def to_hash: -> {
        body: top,
        x_language: top,
        x_sdk_version: top,
        x_sent_at: top,
        x_stream_response: top,
        request_options: Stagehand::RequestOptions
      }
    end
  end
end
