module Stagehand
  module Models
    type session_end_params =
      {  } & Stagehand::Internal::Type::request_parameters

    class SessionEndParams < Stagehand::Internal::Type::BaseModel
      extend Stagehand::Internal::Type::RequestParameters::Converter
      include Stagehand::Internal::Type::RequestParameters

      def initialize: (?request_options: Stagehand::request_opts) -> void

      def to_hash: -> { request_options: Stagehand::RequestOptions }
    end
  end
end
