module Stagehand
  module Resources
    class Sessions
      def start: (
        ?body: top,
        ?x_language: top,
        ?x_sdk_version: top,
        ?x_sent_at: top,
        ?x_stream_response: top,
        ?request_options: Stagehand::request_opts
      ) -> top

      def initialize: (client: Stagehand::Client) -> void
    end
  end
end
