module StagehandSDK
  module Models
    type session_act_params =
      {
        input: StagehandSDK::Models::SessionActParams::input,
        frame_id: String,
        options: StagehandSDK::SessionActParams::Options,
        x_sent_at: Time,
        x_stream_response: StagehandSDK::Models::SessionActParams::x_stream_response
      }
      & StagehandSDK::Internal::Type::request_parameters

    class SessionActParams < StagehandSDK::Internal::Type::BaseModel
      extend StagehandSDK::Internal::Type::RequestParameters::Converter
      include StagehandSDK::Internal::Type::RequestParameters

      attr_accessor input: StagehandSDK::Models::SessionActParams::input

      attr_reader frame_id: String?

      def frame_id=: (String) -> String

      attr_reader options: StagehandSDK::SessionActParams::Options?

      def options=: (
        StagehandSDK::SessionActParams::Options
      ) -> StagehandSDK::SessionActParams::Options

      attr_reader x_sent_at: Time?

      def x_sent_at=: (Time) -> Time

      attr_reader x_stream_response: StagehandSDK::Models::SessionActParams::x_stream_response?

      def x_stream_response=: (
        StagehandSDK::Models::SessionActParams::x_stream_response
      ) -> StagehandSDK::Models::SessionActParams::x_stream_response

      def initialize: (
        input: StagehandSDK::Models::SessionActParams::input,
        ?frame_id: String,
        ?options: StagehandSDK::SessionActParams::Options,
        ?x_sent_at: Time,
        ?x_stream_response: StagehandSDK::Models::SessionActParams::x_stream_response,
        ?request_options: StagehandSDK::request_opts
      ) -> void

      def to_hash: -> {
        input: StagehandSDK::Models::SessionActParams::input,
        frame_id: String,
        options: StagehandSDK::SessionActParams::Options,
        x_sent_at: Time,
        x_stream_response: StagehandSDK::Models::SessionActParams::x_stream_response,
        request_options: StagehandSDK::RequestOptions
      }

      type input = String | StagehandSDK::Action

      module Input
        extend StagehandSDK::Internal::Type::Union

        def self?.variants: -> ::Array[StagehandSDK::Models::SessionActParams::input]
      end

      type options =
        {
          model: StagehandSDK::Models::model_config,
          timeout: Float,
          variables: ::Hash[Symbol, String]
        }

      class Options < StagehandSDK::Internal::Type::BaseModel
        attr_reader model: StagehandSDK::Models::model_config?

        def model=: (
          StagehandSDK::Models::model_config
        ) -> StagehandSDK::Models::model_config

        attr_reader timeout: Float?

        def timeout=: (Float) -> Float

        attr_reader variables: ::Hash[Symbol, String]?

        def variables=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        def initialize: (
          ?model: StagehandSDK::Models::model_config,
          ?timeout: Float,
          ?variables: ::Hash[Symbol, String]
        ) -> void

        def to_hash: -> {
          model: StagehandSDK::Models::model_config,
          timeout: Float,
          variables: ::Hash[Symbol, String]
        }
      end

      type x_stream_response = :true | :false

      module XStreamResponse
        extend StagehandSDK::Internal::Type::Enum

        TRUE: :true
        FALSE: :false

        def self?.values: -> ::Array[StagehandSDK::Models::SessionActParams::x_stream_response]
      end
    end
  end
end
