module StagehandSDK
  module Models
    type session_execute_params =
      {
        agent_config: StagehandSDK::SessionExecuteParams::AgentConfig,
        execute_options: StagehandSDK::SessionExecuteParams::ExecuteOptions,
        frame_id: String?,
        x_stream_response: StagehandSDK::Models::SessionExecuteParams::x_stream_response
      }
      & StagehandSDK::Internal::Type::request_parameters

    class SessionExecuteParams < StagehandSDK::Internal::Type::BaseModel
      extend StagehandSDK::Internal::Type::RequestParameters::Converter
      include StagehandSDK::Internal::Type::RequestParameters

      attr_accessor agent_config: StagehandSDK::SessionExecuteParams::AgentConfig

      attr_accessor execute_options: StagehandSDK::SessionExecuteParams::ExecuteOptions

      attr_accessor frame_id: String?

      attr_reader x_stream_response: StagehandSDK::Models::SessionExecuteParams::x_stream_response?

      def x_stream_response=: (
        StagehandSDK::Models::SessionExecuteParams::x_stream_response
      ) -> StagehandSDK::Models::SessionExecuteParams::x_stream_response

      def initialize: (
        agent_config: StagehandSDK::SessionExecuteParams::AgentConfig,
        execute_options: StagehandSDK::SessionExecuteParams::ExecuteOptions,
        ?frame_id: String?,
        ?x_stream_response: StagehandSDK::Models::SessionExecuteParams::x_stream_response,
        ?request_options: StagehandSDK::request_opts
      ) -> void

      def to_hash: -> {
        agent_config: StagehandSDK::SessionExecuteParams::AgentConfig,
        execute_options: StagehandSDK::SessionExecuteParams::ExecuteOptions,
        frame_id: String?,
        x_stream_response: StagehandSDK::Models::SessionExecuteParams::x_stream_response,
        request_options: StagehandSDK::RequestOptions
      }

      type agent_config =
        {
          cua: bool,
          model: StagehandSDK::Models::model_config,
          provider: StagehandSDK::Models::SessionExecuteParams::AgentConfig::provider,
          system_prompt: String
        }

      class AgentConfig < StagehandSDK::Internal::Type::BaseModel
        attr_reader cua: bool?

        def cua=: (bool) -> bool

        attr_reader model: StagehandSDK::Models::model_config?

        def model=: (
          StagehandSDK::Models::model_config
        ) -> StagehandSDK::Models::model_config

        attr_reader provider: StagehandSDK::Models::SessionExecuteParams::AgentConfig::provider?

        def provider=: (
          StagehandSDK::Models::SessionExecuteParams::AgentConfig::provider
        ) -> StagehandSDK::Models::SessionExecuteParams::AgentConfig::provider

        attr_reader system_prompt: String?

        def system_prompt=: (String) -> String

        def initialize: (
          ?cua: bool,
          ?model: StagehandSDK::Models::model_config,
          ?provider: StagehandSDK::Models::SessionExecuteParams::AgentConfig::provider,
          ?system_prompt: String
        ) -> void

        def to_hash: -> {
          cua: bool,
          model: StagehandSDK::Models::model_config,
          provider: StagehandSDK::Models::SessionExecuteParams::AgentConfig::provider,
          system_prompt: String
        }

        type provider = :openai | :anthropic | :google | :microsoft

        module Provider
          extend StagehandSDK::Internal::Type::Enum

          OPENAI: :openai
          ANTHROPIC: :anthropic
          GOOGLE: :google
          MICROSOFT: :microsoft

          def self?.values: -> ::Array[StagehandSDK::Models::SessionExecuteParams::AgentConfig::provider]
        end
      end

      type execute_options =
        { instruction: String, highlight_cursor: bool, max_steps: Float }

      class ExecuteOptions < StagehandSDK::Internal::Type::BaseModel
        attr_accessor instruction: String

        attr_reader highlight_cursor: bool?

        def highlight_cursor=: (bool) -> bool

        attr_reader max_steps: Float?

        def max_steps=: (Float) -> Float

        def initialize: (
          instruction: String,
          ?highlight_cursor: bool,
          ?max_steps: Float
        ) -> void

        def to_hash: -> {
          instruction: String,
          highlight_cursor: bool,
          max_steps: Float
        }
      end

      type x_stream_response = :true | :false

      module XStreamResponse
        extend StagehandSDK::Internal::Type::Enum

        TRUE: :true
        FALSE: :false

        def self?.values: -> ::Array[StagehandSDK::Models::SessionExecuteParams::x_stream_response]
      end
    end
  end
end
