module StagehandSDK
  module Models
    type session_observe_params =
      {
        frame_id: String,
        instruction: String,
        options: StagehandSDK::SessionObserveParams::Options,
        x_sent_at: Time,
        x_stream_response: StagehandSDK::Models::SessionObserveParams::x_stream_response
      }
      & StagehandSDK::Internal::Type::request_parameters

    class SessionObserveParams < StagehandSDK::Internal::Type::BaseModel
      extend StagehandSDK::Internal::Type::RequestParameters::Converter
      include StagehandSDK::Internal::Type::RequestParameters

      attr_reader frame_id: String?

      def frame_id=: (String) -> String

      attr_reader instruction: String?

      def instruction=: (String) -> String

      attr_reader options: StagehandSDK::SessionObserveParams::Options?

      def options=: (
        StagehandSDK::SessionObserveParams::Options
      ) -> StagehandSDK::SessionObserveParams::Options

      attr_reader x_sent_at: Time?

      def x_sent_at=: (Time) -> Time

      attr_reader x_stream_response: StagehandSDK::Models::SessionObserveParams::x_stream_response?

      def x_stream_response=: (
        StagehandSDK::Models::SessionObserveParams::x_stream_response
      ) -> StagehandSDK::Models::SessionObserveParams::x_stream_response

      def initialize: (
        ?frame_id: String,
        ?instruction: String,
        ?options: StagehandSDK::SessionObserveParams::Options,
        ?x_sent_at: Time,
        ?x_stream_response: StagehandSDK::Models::SessionObserveParams::x_stream_response,
        ?request_options: StagehandSDK::request_opts
      ) -> void

      def to_hash: -> {
        frame_id: String,
        instruction: String,
        options: StagehandSDK::SessionObserveParams::Options,
        x_sent_at: Time,
        x_stream_response: StagehandSDK::Models::SessionObserveParams::x_stream_response,
        request_options: StagehandSDK::RequestOptions
      }

      type options =
        {
          model: StagehandSDK::Models::model_config,
          selector: String,
          timeout: Float
        }

      class Options < StagehandSDK::Internal::Type::BaseModel
        attr_reader model: StagehandSDK::Models::model_config?

        def model=: (
          StagehandSDK::Models::model_config
        ) -> StagehandSDK::Models::model_config

        attr_reader selector: String?

        def selector=: (String) -> String

        attr_reader timeout: Float?

        def timeout=: (Float) -> Float

        def initialize: (
          ?model: StagehandSDK::Models::model_config,
          ?selector: String,
          ?timeout: Float
        ) -> void

        def to_hash: -> {
          model: StagehandSDK::Models::model_config,
          selector: String,
          timeout: Float
        }
      end

      type x_stream_response = :true | :false

      module XStreamResponse
        extend StagehandSDK::Internal::Type::Enum

        TRUE: :true
        FALSE: :false

        def self?.values: -> ::Array[StagehandSDK::Models::SessionObserveParams::x_stream_response]
      end
    end
  end
end
