module StagehandSDK
  module Models
    type session_extract_response =
      {
        data: StagehandSDK::Models::SessionExtractResponse::Data,
        success: bool
      }

    class SessionExtractResponse < StagehandSDK::Internal::Type::BaseModel
      attr_accessor data: StagehandSDK::Models::SessionExtractResponse::Data

      attr_accessor success: bool

      def initialize: (
        data: StagehandSDK::Models::SessionExtractResponse::Data,
        success: bool
      ) -> void

      def to_hash: -> {
        data: StagehandSDK::Models::SessionExtractResponse::Data,
        success: bool
      }

      type data = { result: top, action_id: String }

      class Data < StagehandSDK::Internal::Type::BaseModel
        attr_accessor result: top

        attr_reader action_id: String?

        def action_id=: (String) -> String

        def initialize: (result: top, ?action_id: String) -> void

        def to_hash: -> { result: top, action_id: String }
      end
    end
  end
end
